# Generated by Django 3.2.6 on 2021-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210806_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_patient',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
