# Generated by Django 3.2.6 on 2021-08-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_message_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='questions_asked',
            field=models.CharField(default=False, max_length=1000),
            preserve_default=False,
        ),
    ]
