# Generated by Django 3.2.6 on 2021-08-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_message_questions_asked'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_question',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
