# Generated by Django 3.2.6 on 2021-08-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_sent_by_nurse'),
        ('app', '0006_remove_message_questions_asked'),
    ]

    operations = [
    ]
