# Generated by Django 3.2.6 on 2021-08-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20210806_2136'),
        ('app', '0007_message_is_question'),
    ]

    operations = [
    ]
