# Generated by Django 3.2.6 on 2021-08-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_message_is_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_answer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
