# Generated by Django 3.2.6 on 2021-08-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_is_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_answer',
            field=models.IntegerField(),
        ),
    ]
