# Generated by Django 3.2.6 on 2021-08-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_sent_by_nurse'),
        ('app', '0009_alter_message_is_answer'),
    ]

    operations = [
    ]
