# Generated by Django 3.2.6 on 2021-08-07 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_message_date_created'),
        ('app', '0010_merge_20210806_1855'),
    ]

    operations = [
    ]
