# Generated by Django 3.2.6 on 2021-08-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20210806_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='finished_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_symptomatic', models.BooleanField(default=False)),
                ('not_isolating', models.BooleanField(default=False)),
                ('attending_public', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
