# Generated by Django 3.2.6 on 2021-08-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210806_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dying',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='finished_chat',
        ),
        migrations.AddField(
            model_name='patient',
            name='risk_to_others',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='risk_to_self',
            field=models.IntegerField(default=0),
        ),
    ]
