# Generated by Django 3.2.6 on 2021-08-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210807_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='asked_about_symptoms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='risk_to_others',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='risk_to_self',
            field=models.IntegerField(default=-1),
        ),
    ]
